# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app

# Install Flask
RUN pip install Flask

# Expose port 5000 to the host machine
EXPOSE 5000

# Run the server
ENTRYPOINT ["python", "server.py"]

